### PR TITLE
Update to NetHack 3.6.7

### PR DESCRIPTION
**Pull request by mmatuska**
This PR merges the "NetHack-3.6.7_Released" tag and adds a GitHub actions build.
The GitHub actions build uploads the release apk as an artifact that can be downloaded from the "Actions" menu and tested on Android devices and emulators (and also used for release building in the future).

### CODE REVIEW

**Comment by gurrhack** [comment]
👍 Will review it later this week

**Comment by mmatuska** [comment]
> 👍 Will review it later this week

I think we well need more fixing here.
It does not build with any later than ubuntu 20.04 (using 22.04 action runner you end up in compilation errors).
And on 20.04 actions complete the build but don't install after signing with developer key.

**Comment by gurrhack** [comment]
Perhaps you can remove the workflow for now and I'll approve and merge the rest.

**Comment by gurrhack** [comment]
I was able to make it build locally using Ubuntu 23.04 with Gradle 6.7.1 and Java 11.

With Gradle 7.6.x you'll also have to update `com.android.tools.build` to 7.4.2 and run Java 19. It still doesn't build because of some dependency error, so I gave up on that. It might be because the ForkFront library is built with an older version.

**Comment by mmatuska** [comment]
So I have reduced this PR to just a 3.6.7 update.
But it would still be nice to have the automated build, maybe another PR.
